nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: quick_start.md
      - Installation Guide: installing_guide.md
      - Architecture: architecture.md
      - Environment Variables: environment_variable_configuration.md
  - Feature Guides:
      - Cache: features/cache.md
      - Compilation: features/compilation.md
      - DyEPLB: features/DyEPLB.md
      - Graphics Memory Optimization: features/graphics_memory_optimization.md
      - Others: features/others.md
      - Parallelism: features/parallelism.md
      - Sparse Quantization: features/sparse_quantization.md
      - Support Matrix: features/supported_matrix.md
  - Developer Docs:
      - Build Guide: developer_guide/build_guide.md
      - Test: developer_guide/test.md
      - Tooling: developer_guide/tooling.md
  - Appendix:
      - Environment Variables: appendix/environment_variable.md
      - File Permissions: appendix/file_directory_permissions_description.md
  - Community:
      - Governance: community/governance.md
